[package]
name = "civ6-map-rs"
version = "0.1.0"
authors = ["Max1Truc <maxitruc.bonbec@gmail.com>"]
edition = "2018"
default-run = "civ6-parse-uncompressed"

[dependencies]
flate2 = "1.0.17"
pretty-hex = "0.2.0"
image = "0.23.9"